### ISSUE TITLE
API keys are exposed

### ISSUE THREAD

**Issue by ashishbinu** [phisham/QuestCease_Twitterapi#4]
Hey, you should remove the api keys/secret defined in the `index.js` file in backend folder. Someone can take your twitter api keys and can misuse it. [Here](https://dev.to/getd/how-to-manage-secrets-and-configs-using-dotenv-in-node-js-and-docker-2214)  is how to safely store your api keys for node backend.

**Comment by phisham** [comment]
Thanks for notifying.👍

**Comment by ashishbinu** [comment]
The api keys can be still viewed inside the git commit history. You should rewrite the commit history so as to  not expose your api keys.
